---
title: "IT-PT_Constrasts"
author: "Yasin Kaymaz"
date: "1/31/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(DT)
library(tidyverse)
options(width = 80)
source("https://raw.githubusercontent.com/yasinkaymaz/cellRtools/master/main/functions.R")
load("~/data/markers.L5IT.vs.Gaba.Rdata")
load("~/data/markers.L5IT.vs.Glu.Rdata")
load("~/data/markers.L5IT.vs.Gaba_Glu.Rdata")

FilterTable <- function(DEtable){
  FilteredDETable <- DEtable %>%
    add_column(gene=rownames(DEtable)) %>%
    select(-p_val)%>%
    filter(p_val_adj < 0.01) %>%
    filter(avg_logFC > 0.2) %>%
    filter(pct.1 > 0.5) %>% filter( ((pct.1 - pct.2) > 0.25))

  return(FilteredDETable)
}

InteractiveTable <- function(DEtable){
  library(DT)
  DEtable %>% 
    datatable( extensions = 'Scroller', options = list(
      deferRender = TRUE,
      scrollY = 200,
      scroller = TRUE
    ))
}

```

# IT cells - Contrast against Glutamatergic neurons

```{r echo=FALSE}
InteractiveTable(FilterTable(markers.L5IT.vs.Glu))

```


# IT cells - Contrast against GABAergic neurons

```{r echo=FALSE}
InteractiveTable(FilterTable(markers.L5IT.vs.Gaba))
```

# IT cells - Contrast against both Glutamatergic and GABAergic neurons

```{r echo=FALSE}
InteractiveTable(FilterTable(markers.L5IT.vs.Gaba_Glu))
```


.

.

.

.

.

.

